// GENERATED — do not edit; run `bun contracts/spec/gen-rust.ts`.
import type * as N from "./numeric-microts.ts";
export type i8 = N.i8;
export type i16 = N.i16;
export type i32 = N.i32;
export type i64 = N.i64;
export type u8 = N.u8;
export type u16 = N.u16;
export type u32 = N.u32;
export type u64 = N.u64;
export type usize = N.usize;
export type f32 = N.f32;
export type f64 = N.f64;
export type Px = N.Px;
export type Ms = N.Ms;
export type Deg = N.Deg;
export type Color = N.Color;
export type StyleClass = string & { readonly __style?: true };
export type Cap<T extends string | readonly unknown[], N extends number> = T & { readonly __capacity?: N };
export { copy, equals } from "./model-reactive.ts";
export { capacity as __capacity } from "./model-reactive.ts";
export { frames, after, until, join, all, any, cancel, type Join } from "./model-tasks.ts";
export declare function map<T, U>(value: readonly T[], fn: (value: T, index: i32) => U): U[];
export declare function filter<T>(value: readonly T[], fn: (value: T, index: i32) => boolean): T[];
export declare function find<T>(value: readonly T[], fn: (value: T, index: i32) => boolean): T | undefined;
export declare function some<T>(value: readonly T[], fn: (value: T, index: i32) => boolean): boolean;
export type MicroTsPlainNumber = number & { readonly __type?: never; readonly __newtype?: never };
export type MicroTsNumericResult<T extends number> = T extends MicroTsPlainNumber ? number : T;
export declare function len<T>(value: string | readonly T[]): i32;
export declare function trunc(value: f32 | f64): i32;
export declare function floor(value: f32 | f64): i32;
export declare function ceil(value: f32 | f64): i32;
export declare function round(value: f32 | f64): i32;
export declare function idiv<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function imod<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function min<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function max<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function abs<T extends number>(value: T): MicroTsNumericResult<T>;
export declare function clamp<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber, upper: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function fixed(value: f32 | f64, digits: i32): string;
export declare function i8(value: number): N.i8;
export declare function i16(value: number): N.i16;
export declare function i32(value: number): N.i32;
export declare function i64(value: number): N.i64;
export declare function u8(value: number): N.u8;
export declare function u16(value: number): N.u16;
export declare function u32(value: number): N.u32;
export declare function u64(value: number): N.u64;
export declare function usize(value: number): N.usize;
export declare function f32(value: number): N.f32;
export declare function f64(value: number): N.f64;
export declare function sqrt<T extends N.f32 | N.f64>(value: T): T;
export declare function sin<T extends N.f32 | N.f64>(value: T): T;
export declare function cos<T extends N.f32 | N.f64>(value: T): T;
export declare function tan<T extends N.f32 | N.f64>(value: T): T;
export declare function asin<T extends N.f32 | N.f64>(value: T): T;
export declare function acos<T extends N.f32 | N.f64>(value: T): T;
export declare function atan<T extends N.f32 | N.f64>(value: T): T;
export declare function exp<T extends N.f32 | N.f64>(value: T): T;
export declare function log<T extends N.f32 | N.f64>(value: T): T;
export declare function atan2<T extends N.f32 | N.f64>(value: T, other: NoInfer<T> | MicroTsPlainNumber): T;
export declare function pow<T extends N.f32 | N.f64>(value: T, other: NoInfer<T> | MicroTsPlainNumber): T;
export declare function hypot<T extends N.f32 | N.f64>(value: T, other: NoInfer<T> | MicroTsPlainNumber): T;
export declare function fill<T>(count: N.i32, value: T): T[];
export declare function push<T>(target: T[], value: T): void;
export declare function pop<T>(target: T[]): T;
export declare function insert<T>(target: T[], index: N.i32, value: T): void;
export declare function removeAt<T>(target: T[], index: N.i32): T;
export declare function clear<T>(target: T[]): void;
export declare function truncate<T>(target: T[], length: N.i32): void;
export declare function fillRange<T>(target: T[], start: N.i32, end: N.i32, value: T): void;
export declare function copyRange<T>(target: T[], targetStart: N.i32, source: readonly T[], sourceStart: N.i32, count: N.i32, skip?: T): void;
export declare function fillRect<T>(target: T[], start: N.i32, stride: N.i32, width: N.i32, height: N.i32, value: T): void;
export declare function copyRect<T>(target: T[], targetStart: N.i32, targetStride: N.i32, source: readonly T[], sourceStart: N.i32, sourceStride: N.i32, width: N.i32, height: N.i32, skip?: T): void;
export declare function codePoints(value: string): N.i32[];
export declare function fromCodePoint(code: N.i32): string;
export declare function embedBytes(path: string): N.u8[];
export declare function __colorBits(value: Color): u32;
export declare function __colorText(value: Color | undefined, missing?: string): string;
export declare function __modelNumber(value: number, type: string): number;
export declare function __modelMultiply(left: number, right: number): number;
export declare function __convert(value: number, type: string, float: boolean): number;
